[sakura]
colorset1_fore=rgb(0,255,102)
colorset1_back=rgba(0,0,0,1)
colorset1_curs=rgb(0,255,102)
colorset1_key=F1
last_colorset=1
scroll_lines=5000
font=DejaVu Sans Mono 7
show_always_first_tab=No
show_tab_bar=never
scrollbar=false
closebutton=false
tabs_on_bottom=false
less_questions=true
disable_numbered_tabswitch=false
use_fading=false
scrollable_tabs=true
urgent_bell=Yes
audible_bell=No
blinking_cursor=No
allow_bold=Yes
cursor_type=VTE_CURSOR_SHAPE_BLOCK
word_chars=-,./?%&#_~:
copy_on_select=false
paste_button=2
menu_button=3
add_tab_accelerator=5
del_tab_accelerator=5
switch_tab_accelerator=5
move_tab_accelerator=9
copy_accelerator=5
scrollbar_accelerator=5
open_url_accelerator=5
font_size_accelerator=4
set_tab_name_accelerator=5
add_tab_key=T
del_tab_key=W
prev_tab_key=Left
next_tab_key=Right
copy_key=C
paste_key=V
scrollbar_key=S
set_tab_name_key=N
increase_font_size_key=plus
decrease_font_size_key=minus
fullscreen_key=F11
set_colorset_accelerator=5
