Section "InputClass"
    Identifier "PocketCHIP absolute resistive touchscreen"
    MatchProduct "1c25000.rtp"
    MatchIsTouchscreen "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "CalibrationMatrix" "-1 0 1 0 -1.18 1.09 0 0 1"
EndSection

Section "InputClass"
    Identifier "Ignore PocketCHIP touchscreen mouse compatibility node"
    MatchProduct "1c25000.rtp"
    MatchDevicePath "/dev/input/mouse*"
    Option "Ignore" "true"
EndSection
