export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(git sudo)

if [ -r "$ZSH/oh-my-zsh.sh" ]; then
  . "$ZSH/oh-my-zsh.sh"
fi

export EDITOR=nvim
alias ll='ls -alF'
alias tm='tmux new -A -s pocketchip'

