export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git sudo)

if [ -r "$ZSH/oh-my-zsh.sh" ]; then
  . "$ZSH/oh-my-zsh.sh"
fi

case ":$PATH:" in
  *:/usr/sbin:*) ;;
  *) export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH" ;;
esac
case ":$PATH:" in
  *:"$HOME/.local/bin":*) ;;
  *) export PATH="$PATH:$HOME/.local/bin" ;;
esac

export EDITOR=nvim
export VISUAL=nvim
export PAGER=less
export LESS='-R'
export TERM="${TERM:-xterm-256color}"

setopt autocd interactivecomments magicequalsubst nonomatch notify numericglobsort promptsubst
setopt hist_expire_dups_first hist_ignore_dups hist_ignore_space hist_verify appendhistory
unsetopt sharehistory
WORDCHARS=${WORDCHARS//\/}
PROMPT_EOL_MARK=""

bindkey -e
bindkey ' ' magic-space
bindkey '^U' backward-kill-line
bindkey '^[[3~' delete-char
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[5~' beginning-of-buffer-or-history
bindkey '^[[6~' end-of-buffer-or-history
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey '^[[Z' undo

mkdir -p "$HOME/.cache"
autoload -Uz compinit
compinit -d "$HOME/.cache/zcompdump"
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' rehash true
zstyle ':completion:*' verbose true
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

HISTFILE="$HOME/.zsh_history"
HISTSIZE=1000
SAVEHIST=2000
TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S\ncpu\t%P'

if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot="$(cat /etc/debian_chroot)"
fi

PROMPT_ALTERNATIVE="${PROMPT_ALTERNATIVE:-twoline}"
NEWLINE_BEFORE_PROMPT="${NEWLINE_BEFORE_PROMPT:-yes}"

configure_prompt() {
  case "$PROMPT_ALTERNATIVE" in
    twoline)
      PROMPT=$'%F{green}+--${debian_chroot:+($debian_chroot)-}${VIRTUAL_ENV:+($(basename $VIRTUAL_ENV))-}(%B%F{blue}%n@%m%b%F{green})-[%B%F{reset}%(6~.%-1~/.../%4~.%5~)%b%F{green}]\n+-%B%F{blue}$%b%F{reset} '
      RPROMPT=''
      ;;
    oneline)
      PROMPT=$'${debian_chroot:+($debian_chroot)}${VIRTUAL_ENV:+($(basename $VIRTUAL_ENV))}%B%F{blue}%n@%m%b%F{reset}:%B%F{green}%~%b%F{reset}%# '
      RPROMPT=''
      ;;
    backtrack)
      PROMPT=$'${debian_chroot:+($debian_chroot)}${VIRTUAL_ENV:+($(basename $VIRTUAL_ENV))}%B%F{red}%n@%m%b%F{reset}:%B%F{blue}%~%b%F{reset}%# '
      RPROMPT=''
      ;;
  esac
}

configure_prompt

toggle_oneline_prompt() {
  if [ "$PROMPT_ALTERNATIVE" = oneline ]; then
    PROMPT_ALTERNATIVE=twoline
  else
    PROMPT_ALTERNATIVE=oneline
  fi
  configure_prompt
  zle reset-prompt
}
zle -N toggle_oneline_prompt
bindkey ^P toggle_oneline_prompt

case "$TERM" in
  xterm*|rxvt*|Eterm|aterm|kterm)
    TERM_TITLE=$'\e]0;${debian_chroot:+($debian_chroot)}${VIRTUAL_ENV:+($(basename $VIRTUAL_ENV))}%n@%m: %~\a'
    ;;
  *)
    TERM_TITLE=''
    ;;
esac

precmd() {
  [ -n "$TERM_TITLE" ] && print -Pnr -- "$TERM_TITLE"
  if [ "$NEWLINE_BEFORE_PROMPT" = yes ]; then
    if [ -z "${_NEW_LINE_BEFORE_PROMPT:-}" ]; then
      _NEW_LINE_BEFORE_PROMPT=1
    else
      print ""
    fi
  fi
}

if [ -x /usr/bin/dircolors ]; then
  test -r "$HOME/.dircolors" && eval "$(dircolors -b "$HOME/.dircolors")" || eval "$(dircolors -b)"
  export LS_COLORS="$LS_COLORS:ow=30;44:"
  alias ls='ls --color=auto'
  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
  alias diff='diff --color=auto'
  alias ip='ip --color=auto'
  export LESS_TERMCAP_mb=$'\E[1;31m'
  export LESS_TERMCAP_md=$'\E[1;36m'
  export LESS_TERMCAP_me=$'\E[0m'
  export LESS_TERMCAP_so=$'\E[01;33m'
  export LESS_TERMCAP_se=$'\E[0m'
  export LESS_TERMCAP_us=$'\E[1;32m'
  export LESS_TERMCAP_ue=$'\E[0m'
  zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
fi

for plugin in \
  /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh \
  /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
do
  [ -r "$plugin" ] && . "$plugin"
done

if [ -n "${ZSH_AUTOSUGGEST_VERSION:-}" ]; then
  ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#999'
fi

if [ -n "${ZSH_HIGHLIGHT_VERSION:-}" ]; then
  ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
  ZSH_HIGHLIGHT_STYLES[unknown-token]=underline
  ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=cyan,bold
  ZSH_HIGHLIGHT_STYLES[path]=bold
  ZSH_HIGHLIGHT_STYLES[arg0]=fg=cyan
  ZSH_HIGHLIGHT_STYLES[bracket-error]=fg=red,bold
fi

[ -r /etc/zsh_command_not_found ] && . /etc/zsh_command_not_found

alias history='history 0'
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias c='clear'
alias zs='source ~/.zshrc'
alias tm='tmux new -A -s pocketchip'
alias starti3='pocketchip-startx'
alias wifi='nmtui'
alias bt='bluetoothctl'
alias connect='pocketchip-connect menu'
alias web='pocketchip-browser'
alias web-light='pocketchip-browser light'
alias cheat='less /usr/share/doc/pocketchip/i3-cheatsheet.md'

tmux-mouse() {
  local current_status
  current_status="$(tmux show-option -gqv mouse 2>/dev/null || printf off)"
  if [ "$current_status" = on ]; then
    tmux set-option -g mouse off
    echo "Tmux mouse mode disabled"
  else
    tmux set-option -g mouse on
    echo "Tmux mouse mode enabled"
  fi
}
